# -*- coding: utf-8 -*-
"""Introducao_machine_learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u9a8A3ARL3NjhrhZiOAOXFjM7F8ozGOH
"""

#features 
#pelo longo?
#perna curta?
#faz au au?

porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]
#classes 1 => Porco | 0 => cachorro 
train_x = [porco1,porco2,porco3,cachorro1,cachorro2,cachorro3]
train_y = [1,1,1,0,0,0]

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(train_x, train_y)

animal_misterioso = [1,1,1]
model.predict([animal_misterioso])

misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0, 1, 1]

previsoes = model.predict(teste_x)

#fazendo Comparaçoes e somando numero de casos verdadeiros
corretos = (previsoes == teste_y).sum()
total = len(teste_x)
taxa_acerto = corretos/total
print("Taxa de Acerto: %.2f" % (taxa_acerto * 100))

from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(teste_y,previsoes)
print("Taxa de Acerto usando accuracy: %.2f" % (taxa_de_acerto * 100))

